### ISSUE TITLE
Is there an option to use helm instead of ido to do completing-read?

### ISSUE THREAD

**Issue by jcs090218** [skeeto/javadoc-lookup#6]
as title.

**Comment by skeeto** [comment]
Customize javadoc-lookup-completing-read-function to a different 
function of your choice. The function you choose needs to have an 
interface similar to completing-read.

**Comment by jcs090218** [comment]
Oh, cool! Thank you! It was my bad, I tried to redefine the variable `javadoc-lookup-completing-read-function`, after I set the variables instead of redefine it. It solved the problem. 
```
(setq javadoc-lookup-completing-read-function #'completing-read)
```
